version: 2
jobs:
  build:
    working_directory: ~/GraphQL.Client/
    docker:
      - image: microsoft/dotnet:2.0-sdk
    environment:
      MY_GET_SOURCE: https://www.myget.org/F/graphql-dotnet/api/v3/index.json
    steps:
      - checkout
      
      # Test
      - restore_cache:
          key: NUGET
      - run: dotnet test ./tests/GraphQL.Common.Tests/GraphQL.Common.Tests.csproj
      - run: dotnet test ./tests/GraphQL.Client.Tests/GraphQL.Client.Tests.csproj
      - save_cache:
          key: NUGET
          paths:
            - ~/.nuget/

      # Pack
      - run: dotnet build --configuration Release ./src/GraphQL.Common/GraphQL.Common.csproj
      - run: dotnet pack --configuration Release ./src/GraphQL.Common/GraphQL.Common.csproj
      - run: dotnet build --configuration Release ./src/GraphQL.Client/GraphQL.Client.csproj
      - run: dotnet pack --configuration Release ./src/GraphQL.Client/GraphQL.Client.csproj

      # Store Artifacts
      - store_artifacts:
          path: ./src/GraphQL.Common/bin/Release/GraphQL.Common.1.0.0-beta2.nupkg
      - store_artifacts:
          path: ./src/GraphQL.Client/bin/Release/GraphQL.Client.1.0.0-beta2.nupkg

      # Deploy
      - deploy:
          name: MyGet
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              dotnet nuget push ./src/GraphQL.Common/bin/Release/GraphQL.Common.1.0.0-beta2.nupkg --api-key $MY_GET_API_KEY --source $MY_GET_SOURCE
              dotnet nuget push ./src/GraphQL.Client/bin/Release/GraphQL.Client.1.0.0-beta2.nupkg --api-key $MY_GET_API_KEY --source $MY_GET_SOURCE
            fi

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build
